const test=require('node:test'),assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path');
const E=require('../shuffle/engine.js');
const begin=(seed=1)=>{const r=E.newRun(seed);E.choose(r,r.choices[0]);return r;};
function withSkill(id){for(let seed=1;seed<1000;seed++){const r=E.newRun(seed);if(r.choices.includes(id)){E.choose(r,id);return r;}}throw Error(id);}
function boss(){return E.restore({version:1,seed:19,rng:19,stage:2,phase:'playing',skills:{boots:2,heart:1},level:3,hp:4,choices:[],rerolls:1,elapsed:1});}
function clearStage(r){r.enemies=[];for(const f of r.friends){r.player.x=f.x;r.player.y=f.y;E.tick(r,.01);}r.player.x=E.WIDTH-76;r.player.y=E.HEIGHT/2;E.tick(r,.01);}
test('each seed produces three distinct legal choices; same seed repeats its draft',()=>{
 for(let seed=1;seed<=300;seed++){const r=E.newRun(seed);assert.equal(new Set(r.choices).size,3);assert.deepEqual(r.choices,E.newRun(seed).choices);assert.ok(r.choices.every(id=>E.SKILLS.some(s=>s.id===id)));}
});
test('only offered cards can be chosen, once per draft',()=>{const r=E.newRun(14),id=r.choices[0];assert.equal(E.choose(r,'injected'),false);assert.equal(E.choose(r,id),true);assert.equal(E.choose(r,id),false);assert.equal(r.level,1);});
test('one reroll per stage is deterministic and does not change skill ranks',()=>{const a=E.newRun(2),b=E.newRun(2);assert.ok(E.reroll(a));E.reroll(b);assert.deepEqual(a.choices,b.choices);assert.equal(E.reroll(a),false);assert.equal(a.level,0);});
test('stage exit remains locked until all three friends are rescued',()=>{const r=begin();r.player.x=1044;r.player.y=360;E.tick(r,.01);assert.equal(r.stage,0);assert.equal(r.phase,'playing');});
test('rescuing and leaving advances to a paused draft, carrying the chosen skills',()=>{const r=begin(),s={...r.skills};clearStage(r);assert.equal(r.stage,1);assert.equal(r.phase,'draft');assert.equal(r.totalRescued,3);assert.deepEqual(r.skills,s);const before=JSON.stringify(r);E.tick(r,1,{x:1});assert.equal(JSON.stringify(r),before);});
test('maxed skills never appear again',()=>{const r=withSkill('shield');clearStage(r);assert.ok(!r.choices.includes('shield'));E.reroll(r);assert.ok(!r.choices.includes('shield'));});
test('the second rescue stage opens the Baltazar encounter, not an endless wave',()=>{const r=begin();clearStage(r);E.choose(r,r.choices[0]);clearStage(r);assert.equal(r.stage,2);E.choose(r,r.choices[0]);assert.ok(r.boss);assert.equal(r.friends.length,0);assert.equal(r.boss.courage,3);});
test('boots increase actual displacement and diagonals remain normalized',()=>{const r=withSkill('boots');r.enemies=[];let p={x:r.player.x,y:r.player.y};E.tick(r,.05,{x:1});assert.ok(r.player.x-p.x>176*.05);const moved=r.player.x-p.x;r.player.x=100;r.player.y=360;E.tick(r,.05,{x:1,y:1});assert.ok(Math.abs(Math.hypot(r.player.x-100,r.player.y-360)-moved)<1e-5);});
test('heart increases maximum hearts and heals exactly one',()=>{const r=withSkill('heart');assert.equal(E.stats(r).maxHp,4);assert.equal(r.hp,4);});
test('shield absorbs one collision; invulnerability prevents consecutive-frame hits',()=>{const r=withSkill('shield');r.player.invulnerable=0;r.enemies[0].x=r.player.x;r.enemies[0].y=r.player.y;E.tick(r,.01);assert.equal(r.hp,3);assert.equal(r.player.shield,false);E.tick(r,.01);assert.equal(r.hp,3);r.player.invulnerable=0;E.tick(r,.01);assert.equal(r.hp,2);});
test('dash has a cooldown, real movement and never tunnels across obstacles',()=>{const r=withSkill('dash');r.enemies=[];r.player.x=345;r.player.y=300;assert.ok(E.dash(r,1,0));assert.equal(E.dash(r,1,0),false);for(let i=0;i<15;i++)E.tick(r,1/60);assert.ok(r.player.x+r.player.r<370);assert.ok(r.player.dashCooldown<3.6);assert.ok(E.clearCircle(r,r.player,r.player.r));});
test('corn is locked without its card; an unlocked decoy attracts the enemy and expires',()=>{const r=withSkill('corn');assert.ok(E.decoy(r));assert.equal(E.decoy(r),false);r.player.y=600;const before={...r.enemies[0]};E.tick(r,.05);assert.ok(Math.hypot(r.enemies[0].x-r.decoy.x,r.enemies[0].y-r.decoy.y)<Math.hypot(before.x-r.decoy.x,before.y-r.decoy.y));for(let i=0;i<420;i++)E.tick(r,1/60);assert.equal(r.decoy,null);const a=withSkill('boots');assert.equal(E.decoy(a),false);});
test('call card increases the rescue radius',()=>{const r=withSkill('call');r.enemies=[];r.player.x=r.friends[0].x-58;r.player.y=r.friends[0].y;E.tick(r,.01);assert.equal(r.rescued,1);});
test('pause and invalid time steps freeze movement, cooldowns and boss state',()=>{const r=boss();E.pause(r,true);const old=JSON.stringify(r);for(const dt of [0,-1,NaN,Infinity,.05])E.tick(r,dt,{x:1});assert.equal(JSON.stringify(r),old);E.pause(r,false);for(const dt of [0,-1,NaN,Infinity]){const before=JSON.stringify(r);E.tick(r,dt,{x:1});assert.equal(JSON.stringify(r),before);}});
test('the boss locks its warning direction before charging, then exposes a counter window',()=>{const r=boss();for(let i=0;i<120;i++)E.tick(r,1/60);assert.equal(r.boss.mode,'warning');const aim=[r.boss.aimX,r.boss.aimY];r.player.y=620;for(let i=0;i<30;i++)E.tick(r,1/60);assert.deepEqual([r.boss.aimX,r.boss.aimY],aim);for(let i=0;i<180&&r.boss.mode!=='stunned';i++)E.tick(r,1/60);assert.equal(r.boss.mode,'stunned');});
test('boss counter requires proximity and an opening; one hit per opening wins in three',()=>{const r=boss();assert.equal(E.interact(r),false);for(let hit=0;hit<3;hit++){r.boss.mode='stunned';r.boss.timer=2;r.boss.hitThisStun=false;r.player.x=100;r.player.y=100;assert.equal(E.interact(r),false);r.player.x=r.boss.x-36;r.player.y=r.boss.y;assert.ok(E.interact(r));assert.equal(E.interact(r),false);}assert.equal(r.phase,'won');assert.equal(r.boss.courage,0);});
test('a player can lose; late inputs cannot resume a finished game',()=>{const r=begin();r.player.invulnerable=0;r.player.shield=false;r.hp=1;r.enemies[0].x=r.player.x;r.enemies[0].y=r.player.y;E.tick(r,.01);assert.equal(r.phase,'lost');assert.equal(r.hp,0);assert.equal(E.dash(r,1,0),false);assert.equal(E.decoy(r),false);});
test('draft checkpoint preserves choices, reroll allowance and deterministic next offers',()=>{const r=E.newRun(128);E.reroll(r);const copy=E.restore(JSON.parse(JSON.stringify(E.checkpoint(r))));assert.ok(copy);assert.deepEqual(copy.choices,r.choices);assert.equal(copy.rerolls,0);E.choose(r,r.choices[0]);E.choose(copy,copy.choices[0]);clearStage(r);clearStage(copy);assert.deepEqual(r.choices,copy.choices);});
test('playing checkpoint restarts the phase without touching classic game state',()=>{const r=withSkill('heart'),c=E.checkpoint(r);r.player.x=200;const copy=E.restore(c);assert.ok(copy);assert.equal(copy.player.x,100);assert.deepEqual(copy.skills,r.skills);assert.equal(copy.hp,4);});
test('malformed, unknown and over-ranked checkpoints are rejected',()=>{const good=E.checkpoint(begin());for(const bad of [null,{}, {...good,version:99},{...good,stage:50},{...good,skills:{hacked:1}},{...good,hp:Infinity},{...good,skills:{heart:99}},{...good,level:99},{...good,phase:'won'},{...good,choices:'wrong'}])assert.equal(E.restore(bad),null);});
test('the prototype uses its own local save and reuses PixelLab atlases without game globals',()=>{const ui=fs.readFileSync(path.join(__dirname,'../shuffle/ui.js'),'utf8');assert.match(ui,/penas-pro-ar\.shuffle\.v1/);assert.match(ui,/PixelLabArtData/);assert.doesNotMatch(ui,/GameManager\.|resetGame\(|\.env|api\.pixellab/);});
