// Individual model sheets: keep these identities stable across every direction.
const directions = Object.freeze({ south: 'down', 'south-west': 'downleft', west: 'left', 'north-west': 'upleft', north: 'up', 'north-east': 'upright', east: 'right', 'south-east': 'downright' });
const style = 'Cute original farm-adventure pixel art, rounded chunky silhouettes, warm limited palette, expressive bright eyes, readable face, clean dark one-pixel outlines, deliberate pixel clusters, two-tone shading. Distinct lovable personality, no glossy 3D or fine fur texture. Same low top-down orthographic camera for every view. Entire body, ears, feet and tail visible, transparent background, no ground or shadow, generous empty margin. Preserve anatomy, proportions, markings and the same physical left and right ears in every rotation.';
// id, template, game height, design, locomotion
const entries = [
  ['skin-pacoca','dog',46,'Paçoca, a cheerful caramel mixed-breed puppy, chunky cream muzzle and chest, red triangular bandana, brown oval nose, long upward curved caramel tail. Exactly TWO ears: his anatomical LEFT ear folds forward, RIGHT ear stands upright. Exactly FOUR cream-tipped paws, on all fours. Clear cute canine silhouette.','dog'],
  ['chicken','mannequin',52,'Erina, a brave white farm hen with a pear-shaped body, cream wing tips, three-lobed red comb, little red wattle, amber beak and two broad orange three-toed feet. Confident eyebrows, warm smile, short fan tail. Two wings, no arms.','bird'],
  ['sheep','horse',52,'A cuddly cream sheep with a broad cloud-shaped fleece, peach oval face, two sideways drooping peach ears, small dark muzzle, tiny forehead curl, FOUR clearly separated short legs with brown split hooves. Timid curious personality, no dog nose.','hoof'],
  ['pig','dog',46,'A plump strawberry-pink pig with a bean-shaped torso, big round darker pink snout with two nostrils, floppy triangular ears, tiny curly tail and FOUR short legs ending in dark split hooves. Mischievous smile.','hoof'],
  ['cow','horse',85,'A gentle cream dairy cow with large cocoa-brown irregular patches, broad pink muzzle, tiny ivory horns, wide sideways ears, FOUR sturdy legs with split brown hooves, small udder, thin tufted tail. Kind sleepy oval eyes.','hoof'],
  ['dog','dog',44,'A playful tricolor beagle, cocoa saddle, white face blaze, tan cheeks, TWO long floppy cocoa ears, teal collar with round brass tag, FOUR white sock paws, white-tipped tail, rounded puppy muzzle.','dog'],
  ['cat','cat',34,'A curious ginger tabby cat, round feline cheeks, short muzzle, small pink triangle nose, white whiskerpads, amber eyes, dark ginger forehead stripes, small triangular ears, FOUR white paws, long slender striped tail with NO white fluffy tip.','cat'],
  ['rabbit','cat',38,'A round cinnamon rabbit, two very long upright ears with pink inner ears, cream belly, tiny triangle nose, chubby cheeks, small round white cotton tail. FOUR paws, oversized muscular hind feet and small forepaws. Curious lively face.','rabbit'],
  ['duck','mannequin',37,'A cheerful mallard DUCK with a smooth ROUND emerald bird head, NO external ears, NO horns, NO pointed head tufts. Thin cream neck ring, cinnamon chest, tan body, wide flat ochre duck bill, little curled feather tail and TWO orange webbed feet. Exactly two folded feather wings, waddling posture. Pure duck anatomy, no mammalian features.','bird'],
  ['horse','horse',98,'A friendly chestnut pony, broad cream blaze and muzzle, chocolate forelock and mane, compact strong torso, FOUR cream sock legs with dark hooves, long chocolate tail. Playful proud eyebrows.','hoof'],
  ['donkey','horse',82,'A bashful slate-gray donkey with two very long upright ears, shaggy charcoal forelock, cream muzzle and belly, FOUR sturdy short legs with dark hooves, thin tail ending in a black tuft.','hoof'],
  ['goat','horse',58,'A spirited cream goat, caramel face patches, TWO small backward curved horns, pointed ears, little goatee, short raised tail, FOUR agile legs with split hooves, curious horizontal-pupil eyes.','hoof'],
  ['lamb','horse',39,'A tiny buttery-white lamb, compact fluffy body, little rounded cream face, peach ears sticking sideways, small curl, FOUR short legs with caramel hooves. Shy gentle expression, smaller and rounder than the adult sheep.','hoof'],
  ['chick','mannequin',23,'A tiny lemon-yellow chick, round egg-shaped body, two little feather tufts, tiny orange triangular beak, two stubby wings, two orange three-toed feet, bright curious black eyes.','bird'],
  ['turkey','mannequin',52,'A proud plump cocoa turkey, small burgundy head, red wattle, golden beak, neat fan-shaped russet-and-cream striped tail, two sturdy ochre feet, folded brown wings. Funny dignified face.','bird'],
  ['wolf','dog',72,'A cute theatrical gray wolf, charcoal back and ear tips, cream muzzle cheeks chest and paws, shaggy cheek silhouette, TWO pointed ears, FOUR strong paws, big fluffy gray tail with cream underside, dark bushy eyebrows. Lovable schemer, no snarling horror.','dog'],
  ['hen-silkie','mannequin',52,'Midori, a cute WHITE SILKIE BANTAM HEN, the Japanese silky chicken in this farm cast. Distinctive large ROUND POMPOM FEATHER CREST on her head, rounded cotton-ball body of soft ivory SILKY PLUMAGE, fluffy cheeks and beard. Small charcoal face with two visible bright black eyes, short dark slate beak and tiny turquoise earlobes. NO red comb, NO large red wattles, NO smooth ordinary hen neck. TWO separate short legs wearing fluffy white FEATHER BOOTS down to the toes, small dark toes visible below each foot. Two rounded folded fluffy wings and a short round fluffy tail, NOT an upright fan of long smooth feathers. Sweet alert personality, compact chubby silhouette. Crest, body fluff and feathered feet stay unmistakable in every view.','bird'],
  ['hen-blue','mannequin',52,'Alzira, a confident slate-blue hen, dark navy wings and tail, paler blue chest and cheeks, small bright red comb, golden beak and TWO golden three-toed feet. Angular confident brows on a round cute face.','bird'],
  ['skin-zeca','mannequin',45,'Zeca, a cream-white duck wearing a little straw hat with green band, broad ochre bill, orange webbed feet, round belly, two folded wings, cheeky happy eyes. Hat stays the same size and orientation relative to his head.','bird'],
  ['skin-pipoca','cat',42,'Pipoca, a cream-and-cinnamon rabbit wearing a green triangular neckerchief. Anatomical LEFT long ear upright, RIGHT long ear folds forward at the tip, pink inner ears, short cream muzzle, four paws with large hind feet, cotton white tail. Excitable smile.','rabbit'],
  ['skin-amora','cat',39,'Stella, a charcoal-and-cream tuxedo CAT with short feline muzzle, tiny pink triangular nose, little whiskers, two pointed cat ears, lilac bow at the throat, FOUR white sock paws and a long thin dark tail. Graceful clever expression, never a dog muzzle.','cat'],
  ['skin-gumercindo','mannequin',58,'Gumercindo, a round friendly gray goose with pale cream cheeks, long curved neck, big orange bill, two orange webbed feet, darker gray wings, burgundy-and-cream checked neckerchief. Jolly slightly pompous smile.','bird'],
  ['goose','mannequin',64,'Panto, a stout white guard goose, long curved neck, cream wings, vivid orange broad bill and two large orange webbed feet, little swept forehead feather. Cute bossy eyebrows, theatrical chest.','bird'],
  ['fox','dog',48,'A sly cute russet fox with a compact slender torso, big triangular dark-tipped ears, cream cheeks and muzzle, FOUR dark chocolate sock paws, magnificent russet brush tail with cream tip. Bright green eyes, sly smile.','dog'],
  ['amanda','dog',48,'Amanda, a golden-russet vixen with cream cheek tufts and belly, a small pink bow at the throat, FOUR dark chocolate sock paws, large ears and a broad cream-tipped brush tail. Confident lively emerald eyes.','dog'],
  ['thor','dog',66,'Thor, a cute recognizable purebred GOLDEN RETRIEVER adult dog standing naturally on ALL FOUR PAWS. Long golden honey-colored silky fur, feathered chest and hind legs, two pendant golden ears hanging alongside cheeks, elongated retriever muzzle, small black nose ONLY at the tip, kind dark eyes and warm open smile. The face is all golden, no black mask. Long flowing feathered tail hangs naturally behind him, never curled over the back. Blue collar with one round brass medallion. Four sturdy separate golden paws, balanced horizontal back, raised hips and extended rear legs, ready to walk. Rounded expressive game-cartoon proportions while preserving unmistakable Golden Retriever breed. Not a pug, bulldog, mastiff, shepherd or short-haired mixed breed.','dog'],
  ['owl','mannequin',46,'A plump tawny owl with a rounded heart-shaped cream facial disk, huge expressive amber eyes, small gold hooked beak, two short ear tufts, chocolate speckled wings, two small gold talon feet, little round tail. Comically nosy watchman.','owl'],
  ['scarecrow','mannequin',108,'A lovable farm scarecrow with a round burlap face, stitched smile, button eyes, broad ragged straw hat, moss-green shirt, rust neckerchief, two straw mitten hands on outstretched sleeves, patched overalls fixed to ONE central wooden stake. No walking legs, friendly lopsided eyebrows.','post'],
  ['crow','mannequin',29,'A small cute clever CROW BIRD, pure avian anatomy. Smooth ROUND charcoal feathered head, NO external ears, NO horns, NO antennae, NO mammal features. Broad rounded dark-gray bird beak, bright pearl eyes, completely charcoal body with navy blue wing highlights, TWO feathered wings, TWO small dark talon feet, short flat feather fan tail. NO cream belly, NO fur, NO fluffy mammal tail. Cheeky curious bird expression.','crow'],
];
const gaits = {
  dog: 'Natural four-legged walk, four independently articulated paws. Alternating fore and hind contacts, balanced equal left/right steps, planted paws travel backward while the lifted paws swing forward. No limping or sliding.',
  cat: 'Graceful four-legged feline walk with distinct forepaws and hind paws, correct elbow and hock bends, equal left/right support and soft tail follow-through.',
  hoof: 'Gentle four-beat quadruped walk, four distinct legs and hooves, sequential hind and fore contacts, weight supported by grounded hooves, smooth lifted recovery and stable torso.',
  rabbit: 'Rabbit hop with FOUR paws: small forepaws land first, both muscular hind legs tuck and push off together, brief suspended phase, soft landing. Ears follow through without changing shape.',
  bird: 'Two-foot alternating bird walk, distinct planted and swinging toes, knees bend naturally, balanced slight waddle, two folded wings with subtle follow-through.',
  owl: 'Perched idle, feet stay on the branch plane, gentle breathing, inquisitive head tilt and occasional blink, wings remain folded.',
  crow: 'A full rhythmic flight wingbeat, wings spread to reveal feathers, upstroke, downstroke and bent recovery, feet tucked, fixed camera and body pivot.',
  post: 'Fixed wooden stake remains planted, gentle cloth sway, straw hands and hat brim follow the breeze, subtle lively head nod. Never translate or walk.',
};
function actionsFor(item) {
  const avian=['bird','owl','crow'].includes(item.gait);
  const common = 'One seamless in-place loop, no camera motion or zoom, no translation across canvas, fixed body size and pivot. Preserve all markings, appendages and transparent margins. Keep head and torso facing the original direction throughout the cycle; no turning toward camera in back views. '+(avian?'Pure avian anatomy, two feet, two feathered wings, no mammalian ears or horns. ':'Preserve all four paws and the original ears. ')+
    (item.id==='hen-silkie'?'Keep the fluffy Silkie crest, cottony ivory plumage, dark face, feathered legs and dark toes in every frame. ':item.id==='thor'?'Preserve Golden Retriever breed, long golden feathered coat, pendant ears, long muzzle, blue collar and brass medallion. ':'');
  const gait = gaits[item.gait];
  const run = ({dog:'Natural four-legged running cycle, coordinated diagonal support and flight phases, FOUR complete articulated paws, equal left/right reach, powerful hind-leg push-off, bent recovery and soft landing. No sliding or limping.',
    cat:'Natural bounding feline run on FOUR paws, hind legs gather and push off, forepaws reach and absorb landing, flexible spine with stable body volume and long tail following through.',
    hoof:'A balanced lively four-legged trot, opposite fore and hind hooves move together in diagonal pairs, clear support, brief suspension and recovery. FOUR complete legs, consistent hocks and split hooves.',
    rabbit:gaits.rabbit,
    bird:'Quick two-foot bird run, alternating webbed feet or toes appropriate to this bird, clear push-off, lifted recovery, slightly forward body lean, wings remain wings.'})[item.gait] || gait;
  const actions = {
    walk: common + gait,
    happy: common + gait + ' Cheerful joyful expression, smiling mouth, bright happy eyes; slight lively bounce.',
    scared: common + run + ' Afraid expression, wide eyes, lifted inner brows, worried mouth. '+(avian?'Feathers retain their original shape.':'Ears react but retain their anatomy and identity.'),
    angry: common + (['wolf','fox','amanda','goose'].includes(item.id)?run:gait) + ' Cute grumpy expression, furrowed brows and determined mouth; not aggressive or frightening.',
    sad: common + gait + ' Sad expression, drooping eyelids and mouth, head slightly lowered, small watery eyes.',
  };
  if (!['owl','post','crow'].includes(item.gait)) actions.run = common + run + ' Increased stride and a determined face.';
  if (item.id === 'owl') {
    actions.alert = 'A single 12-pose acting sequence: frame 1 perched relaxed, frames 2-5 spot the player, eyes widen, head turns and chest inhales; frames 6-12 open beak and spread wings to make a funny toy-siren alarm call. Body stays perched, two talons planted. Same owl, camera and scale; whole wings stay inside frame.';
    actions.fly = common + 'Owl flying in a complete wingbeat loop, broad feathered wings rising, powerful downstroke, folded recovery, talons tucked. Stable round torso and same face.';
  }
  if (item.id === 'goose') actions.alert = 'A 12-pose goose warning sequence: first calm, then spots an intruder and raises neck, then spreads both wings and opens bill to honk, comically bossy. Two webbed feet grounded, complete wings in frame, consistent body scale and camera.';
  return actions;
}
// Calibrate returned view offsets without mirroring or redrawing any pixels.
const cast = entries.map(([id, template, height, description, gait]) => ({ id, template, height, description, gait, viewRotation:id==='fox'?7:['chicken','pig','duck','horse','hen-blue','skin-zeca','skin-pipoca','skin-amora','thor','crow'].includes(id)?1:0 }));
module.exports = { cast, style, directions, actionsFor };
