/* Generated by scripts/build-sprite-data.cjs. Credits: assets/sprites/CREDITS.html */
const SpriteData = {
  "chicken": {
    "scale": 2,
    "poses": {
      "up": {
        "frames": [
          {
            "src": "assets/sprites/sources/chicken.png",
            "x": 0,
            "y": 0,
            "w": 32,
            "h": 32
          },
          {
            "src": "assets/sprites/sources/chicken.png",
            "x": 32,
            "y": 0,
            "w": 32,
            "h": 32
          },
          {
            "src": "assets/sprites/sources/chicken.png",
            "x": 64,
            "y": 0,
            "w": 32,
            "h": 32
          },
          {
            "src": "assets/sprites/sources/chicken.png",
            "x": 32,
            "y": 0,
            "w": 32,
            "h": 32
          }
        ],
        "cx": 16,
        "bottom": 32,
        "top": 3,
        "width": 20,
        "flip": false
      },
      "right": {
        "frames": [
          {
            "src": "assets/sprites/sources/chicken.png",
            "x": 0,
            "y": 32,
            "w": 32,
            "h": 32
          },
          {
            "src": "assets/sprites/sources/chicken.png",
            "x": 32,
            "y": 32,
            "w": 32,
            "h": 32
          },
          {
            "src": "assets/sprites/sources/chicken.png",
            "x": 64,
            "y": 32,
            "w": 32,
            "h": 32
          },
          {
            "src": "assets/sprites/sources/chicken.png",
            "x": 32,
            "y": 32,
            "w": 32,
            "h": 32
          }
        ],
        "cx": 16.5,
        "bottom": 32,
        "top": 6,
        "width": 31,
        "flip": false
      },
      "down": {
        "frames": [
          {
            "src": "assets/sprites/sources/chicken.png",
            "x": 0,
            "y": 64,
            "w": 32,
            "h": 32
          },
          {
            "src": "assets/sprites/sources/chicken.png",
            "x": 32,
            "y": 64,
            "w": 32,
            "h": 32
          },
          {
            "src": "assets/sprites/sources/chicken.png",
            "x": 64,
            "y": 64,
            "w": 32,
            "h": 32
          },
          {
            "src": "assets/sprites/sources/chicken.png",
            "x": 32,
            "y": 64,
            "w": 32,
            "h": 32
          }
        ],
        "cx": 16,
        "bottom": 32,
        "top": 2,
        "width": 20,
        "flip": false
      },
      "left": {
        "frames": [
          {
            "src": "assets/sprites/sources/chicken.png",
            "x": 0,
            "y": 96,
            "w": 32,
            "h": 32
          },
          {
            "src": "assets/sprites/sources/chicken.png",
            "x": 32,
            "y": 96,
            "w": 32,
            "h": 32
          },
          {
            "src": "assets/sprites/sources/chicken.png",
            "x": 64,
            "y": 96,
            "w": 32,
            "h": 32
          },
          {
            "src": "assets/sprites/sources/chicken.png",
            "x": 32,
            "y": 96,
            "w": 32,
            "h": 32
          }
        ],
        "cx": 15.5,
        "bottom": 32,
        "top": 6,
        "width": 31,
        "flip": false
      }
    }
  },
  "wolf": {
    "scale": 0.3,
    "poses": {
      "down": {
        "frames": [
          {
            "src": "assets/sprites/sources/wolf-feroz.png",
            "x": 0,
            "y": 0,
            "w": 315,
            "h": 335,
            "cx": 156.5,
            "bottom": 307,
            "top": 13,
            "width": 143
          },
          {
            "src": "assets/sprites/sources/wolf-feroz.png",
            "x": 315,
            "y": 0,
            "w": 312,
            "h": 335,
            "cx": 155.5,
            "bottom": 310,
            "top": 13,
            "width": 141
          },
          {
            "src": "assets/sprites/sources/wolf-feroz.png",
            "x": 627,
            "y": 0,
            "w": 317,
            "h": 335,
            "cx": 158,
            "bottom": 310,
            "top": 13,
            "width": 140
          },
          {
            "src": "assets/sprites/sources/wolf-feroz.png",
            "x": 944,
            "y": 0,
            "w": 310,
            "h": 335,
            "cx": 154,
            "bottom": 313,
            "top": 13,
            "width": 142
          }
        ],
        "cx": 156.5,
        "bottom": 313,
        "top": 13,
        "width": 143,
        "flip": false
      },
      "left": {
        "frames": [
          {
            "src": "assets/sprites/sources/wolf-feroz.png",
            "x": 0,
            "y": 345,
            "w": 315,
            "h": 265,
            "cx": 161,
            "bottom": 228,
            "top": 27,
            "width": 296
          },
          {
            "src": "assets/sprites/sources/wolf-feroz.png",
            "x": 315,
            "y": 345,
            "w": 312,
            "h": 265,
            "cx": 158.5,
            "bottom": 229,
            "top": 28,
            "width": 299
          },
          {
            "src": "assets/sprites/sources/wolf-feroz.png",
            "x": 627,
            "y": 345,
            "w": 317,
            "h": 265,
            "cx": 159.5,
            "bottom": 227,
            "top": 31,
            "width": 299
          },
          {
            "src": "assets/sprites/sources/wolf-feroz.png",
            "x": 944,
            "y": 345,
            "w": 310,
            "h": 265,
            "cx": 155.5,
            "bottom": 224,
            "top": 31,
            "width": 295
          }
        ],
        "cx": 161,
        "bottom": 229,
        "top": 27,
        "width": 299,
        "flip": false
      },
      "right": {
        "frames": [
          {
            "src": "assets/sprites/sources/wolf-feroz.png",
            "x": 0,
            "y": 635,
            "w": 315,
            "h": 250,
            "cx": 155,
            "bottom": 223,
            "top": 28,
            "width": 292
          },
          {
            "src": "assets/sprites/sources/wolf-feroz.png",
            "x": 315,
            "y": 635,
            "w": 312,
            "h": 250,
            "cx": 152.5,
            "bottom": 222,
            "top": 30,
            "width": 297
          },
          {
            "src": "assets/sprites/sources/wolf-feroz.png",
            "x": 627,
            "y": 635,
            "w": 317,
            "h": 250,
            "cx": 161,
            "bottom": 221,
            "top": 28,
            "width": 312
          },
          {
            "src": "assets/sprites/sources/wolf-feroz.png",
            "x": 944,
            "y": 635,
            "w": 310,
            "h": 250,
            "cx": 149.5,
            "bottom": 220,
            "top": 31,
            "width": 299
          }
        ],
        "cx": 155,
        "bottom": 223,
        "top": 28,
        "width": 312,
        "flip": false
      },
      "up": {
        "frames": [
          {
            "src": "assets/sprites/sources/wolf-feroz.png",
            "x": 0,
            "y": 895,
            "w": 315,
            "h": 359,
            "cx": 156.5,
            "bottom": 330,
            "top": 14,
            "width": 137
          },
          {
            "src": "assets/sprites/sources/wolf-feroz.png",
            "x": 315,
            "y": 895,
            "w": 312,
            "h": 359,
            "cx": 155,
            "bottom": 335,
            "top": 14,
            "width": 136
          },
          {
            "src": "assets/sprites/sources/wolf-feroz.png",
            "x": 627,
            "y": 895,
            "w": 317,
            "h": 359,
            "cx": 157,
            "bottom": 330,
            "top": 14,
            "width": 136
          },
          {
            "src": "assets/sprites/sources/wolf-feroz.png",
            "x": 944,
            "y": 895,
            "w": 310,
            "h": 359,
            "cx": 153,
            "bottom": 336,
            "top": 14,
            "width": 136
          }
        ],
        "cx": 156.5,
        "bottom": 336,
        "top": 14,
        "width": 137,
        "flip": false
      }
    }
  },
  "goose": {
    "scale": 1,
    "poses": {
      "up": {
        "frames": [
          {
            "src": "assets/sprites/sources/goose.png",
            "x": 0,
            "y": 0,
            "w": 64,
            "h": 64
          },
          {
            "src": "assets/sprites/sources/goose.png",
            "x": 64,
            "y": 0,
            "w": 64,
            "h": 64
          }
        ],
        "cx": 31.5,
        "bottom": 60,
        "top": 4,
        "width": 29,
        "flip": false
      },
      "right": {
        "frames": [
          {
            "src": "assets/sprites/sources/goose.png",
            "x": 0,
            "y": 64,
            "w": 64,
            "h": 64
          },
          {
            "src": "assets/sprites/sources/goose.png",
            "x": 64,
            "y": 64,
            "w": 64,
            "h": 64
          }
        ],
        "cx": 35.5,
        "bottom": 60,
        "top": 7,
        "width": 45,
        "flip": false
      },
      "down": {
        "frames": [
          {
            "src": "assets/sprites/sources/goose.png",
            "x": 0,
            "y": 128,
            "w": 64,
            "h": 64
          },
          {
            "src": "assets/sprites/sources/goose.png",
            "x": 64,
            "y": 128,
            "w": 64,
            "h": 64
          }
        ],
        "cx": 32,
        "bottom": 60,
        "top": 6,
        "width": 28,
        "flip": false
      },
      "left": {
        "frames": [
          {
            "src": "assets/sprites/sources/goose.png",
            "x": 0,
            "y": 192,
            "w": 64,
            "h": 64
          },
          {
            "src": "assets/sprites/sources/goose.png",
            "x": 64,
            "y": 192,
            "w": 64,
            "h": 64
          }
        ],
        "cx": 28,
        "bottom": 60,
        "top": 9,
        "width": 48,
        "flip": false
      }
    }
  },
  "sheep": {
    "scale": 1.2,
    "poses": {
      "up": {
        "frames": [
          {
            "src": "assets/sprites/sources/sheep_walk.png",
            "x": 0,
            "y": 0,
            "w": 128,
            "h": 128
          },
          {
            "src": "assets/sprites/sources/sheep_walk.png",
            "x": 128,
            "y": 0,
            "w": 128,
            "h": 128
          },
          {
            "src": "assets/sprites/sources/sheep_walk.png",
            "x": 256,
            "y": 0,
            "w": 128,
            "h": 128
          },
          {
            "src": "assets/sprites/sources/sheep_walk.png",
            "x": 384,
            "y": 0,
            "w": 128,
            "h": 128
          }
        ],
        "cx": 63.5,
        "bottom": 89,
        "top": 39,
        "width": 27,
        "flip": false
      },
      "left": {
        "frames": [
          {
            "src": "assets/sprites/sources/sheep_walk.png",
            "x": 0,
            "y": 128,
            "w": 128,
            "h": 128
          },
          {
            "src": "assets/sprites/sources/sheep_walk.png",
            "x": 128,
            "y": 128,
            "w": 128,
            "h": 128
          },
          {
            "src": "assets/sprites/sources/sheep_walk.png",
            "x": 256,
            "y": 128,
            "w": 128,
            "h": 128
          },
          {
            "src": "assets/sprites/sources/sheep_walk.png",
            "x": 384,
            "y": 128,
            "w": 128,
            "h": 128
          }
        ],
        "cx": 61.5,
        "bottom": 83,
        "top": 43,
        "width": 49,
        "flip": false
      },
      "down": {
        "frames": [
          {
            "src": "assets/sprites/sources/sheep_walk.png",
            "x": 0,
            "y": 256,
            "w": 128,
            "h": 128
          },
          {
            "src": "assets/sprites/sources/sheep_walk.png",
            "x": 128,
            "y": 256,
            "w": 128,
            "h": 128
          },
          {
            "src": "assets/sprites/sources/sheep_walk.png",
            "x": 256,
            "y": 256,
            "w": 128,
            "h": 128
          },
          {
            "src": "assets/sprites/sources/sheep_walk.png",
            "x": 384,
            "y": 256,
            "w": 128,
            "h": 128
          }
        ],
        "cx": 63.5,
        "bottom": 89,
        "top": 47,
        "width": 27,
        "flip": false
      },
      "right": {
        "frames": [
          {
            "src": "assets/sprites/sources/sheep_walk.png",
            "x": 0,
            "y": 384,
            "w": 128,
            "h": 128
          },
          {
            "src": "assets/sprites/sources/sheep_walk.png",
            "x": 128,
            "y": 384,
            "w": 128,
            "h": 128
          },
          {
            "src": "assets/sprites/sources/sheep_walk.png",
            "x": 256,
            "y": 384,
            "w": 128,
            "h": 128
          },
          {
            "src": "assets/sprites/sources/sheep_walk.png",
            "x": 384,
            "y": 384,
            "w": 128,
            "h": 128
          }
        ],
        "cx": 66.5,
        "bottom": 83,
        "top": 43,
        "width": 49,
        "flip": false
      }
    }
  },
  "pig": {
    "scale": 1.05,
    "poses": {
      "up": {
        "frames": [
          {
            "src": "assets/sprites/sources/pig.png",
            "x": 0,
            "y": 0,
            "w": 64,
            "h": 64
          },
          {
            "src": "assets/sprites/sources/pig.png",
            "x": 64,
            "y": 0,
            "w": 64,
            "h": 64
          },
          {
            "src": "assets/sprites/sources/pig.png",
            "x": 128,
            "y": 0,
            "w": 64,
            "h": 64
          },
          {
            "src": "assets/sprites/sources/pig.png",
            "x": 64,
            "y": 0,
            "w": 64,
            "h": 64
          }
        ],
        "cx": 32.5,
        "bottom": 64,
        "top": 16,
        "width": 21,
        "flip": false
      },
      "right": {
        "frames": [
          {
            "src": "assets/sprites/sources/pig.png",
            "x": 0,
            "y": 64,
            "w": 64,
            "h": 64
          },
          {
            "src": "assets/sprites/sources/pig.png",
            "x": 64,
            "y": 64,
            "w": 64,
            "h": 64
          },
          {
            "src": "assets/sprites/sources/pig.png",
            "x": 128,
            "y": 64,
            "w": 64,
            "h": 64
          },
          {
            "src": "assets/sprites/sources/pig.png",
            "x": 64,
            "y": 64,
            "w": 64,
            "h": 64
          }
        ],
        "cx": 34.5,
        "bottom": 64,
        "top": 33,
        "width": 55,
        "flip": false
      },
      "down": {
        "frames": [
          {
            "src": "assets/sprites/sources/pig.png",
            "x": 0,
            "y": 128,
            "w": 64,
            "h": 64
          },
          {
            "src": "assets/sprites/sources/pig.png",
            "x": 64,
            "y": 128,
            "w": 64,
            "h": 64
          },
          {
            "src": "assets/sprites/sources/pig.png",
            "x": 128,
            "y": 128,
            "w": 64,
            "h": 64
          },
          {
            "src": "assets/sprites/sources/pig.png",
            "x": 64,
            "y": 128,
            "w": 64,
            "h": 64
          }
        ],
        "cx": 32.5,
        "bottom": 64,
        "top": 18,
        "width": 21,
        "flip": false
      },
      "left": {
        "frames": [
          {
            "src": "assets/sprites/sources/pig.png",
            "x": 0,
            "y": 192,
            "w": 64,
            "h": 64
          },
          {
            "src": "assets/sprites/sources/pig.png",
            "x": 64,
            "y": 192,
            "w": 64,
            "h": 64
          },
          {
            "src": "assets/sprites/sources/pig.png",
            "x": 128,
            "y": 192,
            "w": 64,
            "h": 64
          },
          {
            "src": "assets/sprites/sources/pig.png",
            "x": 64,
            "y": 192,
            "w": 64,
            "h": 64
          }
        ],
        "cx": 29.5,
        "bottom": 64,
        "top": 33,
        "width": 55,
        "flip": false
      }
    }
  },
  "goat": {
    "scale": 1,
    "poses": {
      "up": {
        "frames": [
          {
            "src": "assets/sprites/sources/goat.png",
            "x": 0,
            "y": 0,
            "w": 64,
            "h": 64
          },
          {
            "src": "assets/sprites/sources/goat.png",
            "x": 64,
            "y": 0,
            "w": 64,
            "h": 64
          },
          {
            "src": "assets/sprites/sources/goat.png",
            "x": 128,
            "y": 0,
            "w": 64,
            "h": 64
          },
          {
            "src": "assets/sprites/sources/goat.png",
            "x": 64,
            "y": 0,
            "w": 64,
            "h": 64
          }
        ],
        "cx": 32,
        "bottom": 64,
        "top": 0,
        "width": 20,
        "flip": false
      },
      "right": {
        "frames": [
          {
            "src": "assets/sprites/sources/goat.png",
            "x": 0,
            "y": 64,
            "w": 64,
            "h": 64
          },
          {
            "src": "assets/sprites/sources/goat.png",
            "x": 64,
            "y": 64,
            "w": 64,
            "h": 64
          },
          {
            "src": "assets/sprites/sources/goat.png",
            "x": 128,
            "y": 64,
            "w": 64,
            "h": 64
          },
          {
            "src": "assets/sprites/sources/goat.png",
            "x": 64,
            "y": 64,
            "w": 64,
            "h": 64
          }
        ],
        "cx": 32,
        "bottom": 64,
        "top": 12,
        "width": 54,
        "flip": false
      },
      "down": {
        "frames": [
          {
            "src": "assets/sprites/sources/goat.png",
            "x": 0,
            "y": 128,
            "w": 64,
            "h": 64
          },
          {
            "src": "assets/sprites/sources/goat.png",
            "x": 64,
            "y": 128,
            "w": 64,
            "h": 64
          },
          {
            "src": "assets/sprites/sources/goat.png",
            "x": 128,
            "y": 128,
            "w": 64,
            "h": 64
          },
          {
            "src": "assets/sprites/sources/goat.png",
            "x": 64,
            "y": 128,
            "w": 64,
            "h": 64
          }
        ],
        "cx": 32,
        "bottom": 64,
        "top": 7,
        "width": 20,
        "flip": false
      },
      "left": {
        "frames": [
          {
            "src": "assets/sprites/sources/goat.png",
            "x": 0,
            "y": 192,
            "w": 64,
            "h": 64
          },
          {
            "src": "assets/sprites/sources/goat.png",
            "x": 64,
            "y": 192,
            "w": 64,
            "h": 64
          },
          {
            "src": "assets/sprites/sources/goat.png",
            "x": 128,
            "y": 192,
            "w": 64,
            "h": 64
          },
          {
            "src": "assets/sprites/sources/goat.png",
            "x": 64,
            "y": 192,
            "w": 64,
            "h": 64
          }
        ],
        "cx": 32,
        "bottom": 64,
        "top": 12,
        "width": 54,
        "flip": false
      }
    }
  },
  "cow": {
    "scale": 1.05,
    "poses": {
      "up": {
        "frames": [
          {
            "src": "assets/sprites/sources/cow_walk.png",
            "x": 0,
            "y": 0,
            "w": 128,
            "h": 128
          },
          {
            "src": "assets/sprites/sources/cow_walk.png",
            "x": 128,
            "y": 0,
            "w": 128,
            "h": 128
          },
          {
            "src": "assets/sprites/sources/cow_walk.png",
            "x": 256,
            "y": 0,
            "w": 128,
            "h": 128
          },
          {
            "src": "assets/sprites/sources/cow_walk.png",
            "x": 384,
            "y": 0,
            "w": 128,
            "h": 128
          }
        ],
        "cx": 64.5,
        "bottom": 112,
        "top": 40,
        "width": 27,
        "flip": false
      },
      "left": {
        "frames": [
          {
            "src": "assets/sprites/sources/cow_walk.png",
            "x": 0,
            "y": 128,
            "w": 128,
            "h": 128
          },
          {
            "src": "assets/sprites/sources/cow_walk.png",
            "x": 128,
            "y": 128,
            "w": 128,
            "h": 128
          },
          {
            "src": "assets/sprites/sources/cow_walk.png",
            "x": 256,
            "y": 128,
            "w": 128,
            "h": 128
          },
          {
            "src": "assets/sprites/sources/cow_walk.png",
            "x": 384,
            "y": 128,
            "w": 128,
            "h": 128
          }
        ],
        "cx": 55.5,
        "bottom": 89,
        "top": 44,
        "width": 71,
        "flip": false
      },
      "down": {
        "frames": [
          {
            "src": "assets/sprites/sources/cow_walk.png",
            "x": 0,
            "y": 256,
            "w": 128,
            "h": 128
          },
          {
            "src": "assets/sprites/sources/cow_walk.png",
            "x": 128,
            "y": 256,
            "w": 128,
            "h": 128
          },
          {
            "src": "assets/sprites/sources/cow_walk.png",
            "x": 256,
            "y": 256,
            "w": 128,
            "h": 128
          },
          {
            "src": "assets/sprites/sources/cow_walk.png",
            "x": 384,
            "y": 256,
            "w": 128,
            "h": 128
          }
        ],
        "cx": 64.5,
        "bottom": 104,
        "top": 45,
        "width": 27,
        "flip": false
      },
      "right": {
        "frames": [
          {
            "src": "assets/sprites/sources/cow_walk.png",
            "x": 0,
            "y": 384,
            "w": 128,
            "h": 128
          },
          {
            "src": "assets/sprites/sources/cow_walk.png",
            "x": 128,
            "y": 384,
            "w": 128,
            "h": 128
          },
          {
            "src": "assets/sprites/sources/cow_walk.png",
            "x": 256,
            "y": 384,
            "w": 128,
            "h": 128
          },
          {
            "src": "assets/sprites/sources/cow_walk.png",
            "x": 384,
            "y": 384,
            "w": 128,
            "h": 128
          }
        ],
        "cx": 71.5,
        "bottom": 89,
        "top": 44,
        "width": 71,
        "flip": false
      }
    }
  },
  "duck": {
    "scale": 0.85,
    "poses": {
      "left": {
        "frames": [
          {
            "src": "assets/sprites/sources/duck-3-1.png",
            "x": 0,
            "y": 0,
            "w": 64,
            "h": 64
          },
          {
            "src": "assets/sprites/sources/duck-3-2.png",
            "x": 0,
            "y": 0,
            "w": 64,
            "h": 64
          },
          {
            "src": "assets/sprites/sources/duck-3-3.png",
            "x": 0,
            "y": 0,
            "w": 64,
            "h": 64
          },
          {
            "src": "assets/sprites/sources/duck-3-4.png",
            "x": 0,
            "y": 0,
            "w": 64,
            "h": 64
          },
          {
            "src": "assets/sprites/sources/duck-3-5.png",
            "x": 0,
            "y": 0,
            "w": 64,
            "h": 64
          },
          {
            "src": "assets/sprites/sources/duck-3-6.png",
            "x": 0,
            "y": 0,
            "w": 64,
            "h": 64
          },
          {
            "src": "assets/sprites/sources/duck-3-7.png",
            "x": 0,
            "y": 0,
            "w": 64,
            "h": 64
          }
        ],
        "cx": 31,
        "bottom": 64,
        "top": 0,
        "width": 50,
        "flip": false
      },
      "down": {
        "frames": [
          {
            "src": "assets/sprites/sources/duck-4-1.png",
            "x": 0,
            "y": 0,
            "w": 64,
            "h": 64
          },
          {
            "src": "assets/sprites/sources/duck-4-2.png",
            "x": 0,
            "y": 0,
            "w": 64,
            "h": 64
          },
          {
            "src": "assets/sprites/sources/duck-4-3.png",
            "x": 0,
            "y": 0,
            "w": 64,
            "h": 64
          },
          {
            "src": "assets/sprites/sources/duck-4-4.png",
            "x": 0,
            "y": 0,
            "w": 64,
            "h": 64
          }
        ],
        "cx": 31,
        "bottom": 64,
        "top": 2,
        "width": 38,
        "flip": false
      },
      "up": {
        "frames": [
          {
            "src": "assets/sprites/sources/duck-5-1.png",
            "x": 0,
            "y": 0,
            "w": 64,
            "h": 64
          },
          {
            "src": "assets/sprites/sources/duck-5-2.png",
            "x": 0,
            "y": 0,
            "w": 64,
            "h": 64
          },
          {
            "src": "assets/sprites/sources/duck-5-3.png",
            "x": 0,
            "y": 0,
            "w": 64,
            "h": 64
          },
          {
            "src": "assets/sprites/sources/duck-5-4.png",
            "x": 0,
            "y": 0,
            "w": 64,
            "h": 64
          }
        ],
        "cx": 34.5,
        "bottom": 64,
        "top": 2,
        "width": 37,
        "flip": false
      },
      "right": {
        "frames": [
          {
            "src": "assets/sprites/sources/duck-3-1.png",
            "x": 0,
            "y": 0,
            "w": 64,
            "h": 64
          },
          {
            "src": "assets/sprites/sources/duck-3-2.png",
            "x": 0,
            "y": 0,
            "w": 64,
            "h": 64
          },
          {
            "src": "assets/sprites/sources/duck-3-3.png",
            "x": 0,
            "y": 0,
            "w": 64,
            "h": 64
          },
          {
            "src": "assets/sprites/sources/duck-3-4.png",
            "x": 0,
            "y": 0,
            "w": 64,
            "h": 64
          },
          {
            "src": "assets/sprites/sources/duck-3-5.png",
            "x": 0,
            "y": 0,
            "w": 64,
            "h": 64
          },
          {
            "src": "assets/sprites/sources/duck-3-6.png",
            "x": 0,
            "y": 0,
            "w": 64,
            "h": 64
          },
          {
            "src": "assets/sprites/sources/duck-3-7.png",
            "x": 0,
            "y": 0,
            "w": 64,
            "h": 64
          }
        ],
        "cx": 31,
        "bottom": 64,
        "top": 0,
        "width": 50,
        "flip": true
      }
    }
  },
  "rabbit": {
    "scale": 1.15,
    "poses": {
      "up": {
        "frames": [
          {
            "src": "assets/sprites/sources/rabbit.png",
            "x": 0,
            "y": 0,
            "w": 48,
            "h": 64
          },
          {
            "src": "assets/sprites/sources/rabbit.png",
            "x": 48,
            "y": 0,
            "w": 48,
            "h": 64
          },
          {
            "src": "assets/sprites/sources/rabbit.png",
            "x": 96,
            "y": 0,
            "w": 48,
            "h": 64
          },
          {
            "src": "assets/sprites/sources/rabbit.png",
            "x": 48,
            "y": 0,
            "w": 48,
            "h": 64
          }
        ],
        "cx": 23.5,
        "bottom": 64,
        "top": 29,
        "width": 19,
        "flip": false
      },
      "right": {
        "frames": [
          {
            "src": "assets/sprites/sources/rabbit.png",
            "x": 0,
            "y": 64,
            "w": 48,
            "h": 64
          },
          {
            "src": "assets/sprites/sources/rabbit.png",
            "x": 48,
            "y": 64,
            "w": 48,
            "h": 64
          },
          {
            "src": "assets/sprites/sources/rabbit.png",
            "x": 96,
            "y": 64,
            "w": 48,
            "h": 64
          },
          {
            "src": "assets/sprites/sources/rabbit.png",
            "x": 48,
            "y": 64,
            "w": 48,
            "h": 64
          }
        ],
        "cx": 24.5,
        "bottom": 62,
        "top": 34,
        "width": 33,
        "flip": false
      },
      "down": {
        "frames": [
          {
            "src": "assets/sprites/sources/rabbit.png",
            "x": 0,
            "y": 128,
            "w": 48,
            "h": 64
          },
          {
            "src": "assets/sprites/sources/rabbit.png",
            "x": 48,
            "y": 128,
            "w": 48,
            "h": 64
          },
          {
            "src": "assets/sprites/sources/rabbit.png",
            "x": 96,
            "y": 128,
            "w": 48,
            "h": 64
          },
          {
            "src": "assets/sprites/sources/rabbit.png",
            "x": 48,
            "y": 128,
            "w": 48,
            "h": 64
          }
        ],
        "cx": 23.5,
        "bottom": 64,
        "top": 33,
        "width": 19,
        "flip": false
      },
      "left": {
        "frames": [
          {
            "src": "assets/sprites/sources/rabbit.png",
            "x": 0,
            "y": 192,
            "w": 48,
            "h": 64
          },
          {
            "src": "assets/sprites/sources/rabbit.png",
            "x": 48,
            "y": 192,
            "w": 48,
            "h": 64
          },
          {
            "src": "assets/sprites/sources/rabbit.png",
            "x": 96,
            "y": 192,
            "w": 48,
            "h": 64
          },
          {
            "src": "assets/sprites/sources/rabbit.png",
            "x": 48,
            "y": 192,
            "w": 48,
            "h": 64
          }
        ],
        "cx": 23.5,
        "bottom": 62,
        "top": 34,
        "width": 33,
        "flip": false
      }
    }
  },
  "dog": {
    "scale": 2,
    "poses": {
      "up": {
        "frames": [
          {
            "src": "assets/sprites/sources/dog-lpc.png",
            "x": 128,
            "y": 32,
            "w": 32,
            "h": 32
          },
          {
            "src": "assets/sprites/sources/dog-lpc.png",
            "x": 160,
            "y": 32,
            "w": 32,
            "h": 32
          },
          {
            "src": "assets/sprites/sources/dog-lpc.png",
            "x": 192,
            "y": 32,
            "w": 32,
            "h": 32
          },
          {
            "src": "assets/sprites/sources/dog-lpc.png",
            "x": 160,
            "y": 32,
            "w": 32,
            "h": 32
          }
        ],
        "cx": 16.5,
        "bottom": 28,
        "top": 2,
        "width": 11,
        "flip": false
      },
      "right": {
        "frames": [
          {
            "src": "assets/sprites/sources/dog-lpc.png",
            "x": 128,
            "y": 0,
            "w": 32,
            "h": 32
          },
          {
            "src": "assets/sprites/sources/dog-lpc.png",
            "x": 160,
            "y": 0,
            "w": 32,
            "h": 32
          },
          {
            "src": "assets/sprites/sources/dog-lpc.png",
            "x": 192,
            "y": 0,
            "w": 32,
            "h": 32
          },
          {
            "src": "assets/sprites/sources/dog-lpc.png",
            "x": 160,
            "y": 0,
            "w": 32,
            "h": 32
          }
        ],
        "cx": 15.5,
        "bottom": 29,
        "top": 7,
        "width": 27,
        "flip": false
      },
      "down": {
        "frames": [
          {
            "src": "assets/sprites/sources/dog-lpc.png",
            "x": 128,
            "y": 64,
            "w": 32,
            "h": 32
          },
          {
            "src": "assets/sprites/sources/dog-lpc.png",
            "x": 160,
            "y": 64,
            "w": 32,
            "h": 32
          },
          {
            "src": "assets/sprites/sources/dog-lpc.png",
            "x": 192,
            "y": 64,
            "w": 32,
            "h": 32
          },
          {
            "src": "assets/sprites/sources/dog-lpc.png",
            "x": 160,
            "y": 64,
            "w": 32,
            "h": 32
          }
        ],
        "cx": 16.5,
        "bottom": 31,
        "top": 5,
        "width": 11,
        "flip": false
      },
      "left": {
        "frames": [
          {
            "src": "assets/sprites/sources/dog-lpc.png",
            "x": 128,
            "y": 96,
            "w": 32,
            "h": 32
          },
          {
            "src": "assets/sprites/sources/dog-lpc.png",
            "x": 160,
            "y": 96,
            "w": 32,
            "h": 32
          },
          {
            "src": "assets/sprites/sources/dog-lpc.png",
            "x": 192,
            "y": 96,
            "w": 32,
            "h": 32
          },
          {
            "src": "assets/sprites/sources/dog-lpc.png",
            "x": 160,
            "y": 96,
            "w": 32,
            "h": 32
          }
        ],
        "cx": 16.5,
        "bottom": 29,
        "top": 7,
        "width": 27,
        "flip": false
      }
    }
  },
  "cat": {
    "scale": 2,
    "poses": {
      "up": {
        "frames": [
          {
            "src": "assets/sprites/sources/cat.png",
            "x": 0,
            "y": 0,
            "w": 32,
            "h": 48
          },
          {
            "src": "assets/sprites/sources/cat.png",
            "x": 32,
            "y": 0,
            "w": 32,
            "h": 48
          },
          {
            "src": "assets/sprites/sources/cat.png",
            "x": 64,
            "y": 0,
            "w": 32,
            "h": 48
          },
          {
            "src": "assets/sprites/sources/cat.png",
            "x": 32,
            "y": 0,
            "w": 32,
            "h": 48
          }
        ],
        "cx": 15.5,
        "bottom": 44,
        "top": 18,
        "width": 13,
        "flip": false
      },
      "right": {
        "frames": [
          {
            "src": "assets/sprites/sources/cat.png",
            "x": 0,
            "y": 48,
            "w": 32,
            "h": 48
          },
          {
            "src": "assets/sprites/sources/cat.png",
            "x": 32,
            "y": 48,
            "w": 32,
            "h": 48
          },
          {
            "src": "assets/sprites/sources/cat.png",
            "x": 64,
            "y": 48,
            "w": 32,
            "h": 48
          },
          {
            "src": "assets/sprites/sources/cat.png",
            "x": 32,
            "y": 48,
            "w": 32,
            "h": 48
          }
        ],
        "cx": 16,
        "bottom": 43,
        "top": 23,
        "width": 24,
        "flip": false
      },
      "down": {
        "frames": [
          {
            "src": "assets/sprites/sources/cat.png",
            "x": 0,
            "y": 96,
            "w": 32,
            "h": 48
          },
          {
            "src": "assets/sprites/sources/cat.png",
            "x": 32,
            "y": 96,
            "w": 32,
            "h": 48
          },
          {
            "src": "assets/sprites/sources/cat.png",
            "x": 64,
            "y": 96,
            "w": 32,
            "h": 48
          },
          {
            "src": "assets/sprites/sources/cat.png",
            "x": 32,
            "y": 96,
            "w": 32,
            "h": 48
          }
        ],
        "cx": 15.5,
        "bottom": 44,
        "top": 19,
        "width": 13,
        "flip": false
      },
      "left": {
        "frames": [
          {
            "src": "assets/sprites/sources/cat.png",
            "x": 0,
            "y": 144,
            "w": 32,
            "h": 48
          },
          {
            "src": "assets/sprites/sources/cat.png",
            "x": 32,
            "y": 144,
            "w": 32,
            "h": 48
          },
          {
            "src": "assets/sprites/sources/cat.png",
            "x": 64,
            "y": 144,
            "w": 32,
            "h": 48
          },
          {
            "src": "assets/sprites/sources/cat.png",
            "x": 32,
            "y": 144,
            "w": 32,
            "h": 48
          }
        ],
        "cx": 16,
        "bottom": 43,
        "top": 23,
        "width": 24,
        "flip": false
      }
    }
  },
  "donkey": {
    "scale": 3,
    "poses": {
      "up": {
        "frames": [
          {
            "src": "assets/sprites/sources/donkey-original.png",
            "x": 96,
            "y": 0,
            "w": 16,
            "h": 16
          },
          {
            "src": "assets/sprites/sources/donkey-original.png",
            "x": 112,
            "y": 0,
            "w": 16,
            "h": 16
          }
        ],
        "cx": 8,
        "bottom": 16,
        "top": 1,
        "width": 10,
        "flip": false
      },
      "right": {
        "frames": [
          {
            "src": "assets/sprites/sources/donkey-original.png",
            "x": 96,
            "y": 16,
            "w": 16,
            "h": 16
          },
          {
            "src": "assets/sprites/sources/donkey-original.png",
            "x": 112,
            "y": 16,
            "w": 16,
            "h": 16
          }
        ],
        "cx": 8,
        "bottom": 15,
        "top": 0,
        "width": 16,
        "flip": false
      },
      "down": {
        "frames": [
          {
            "src": "assets/sprites/sources/donkey-original.png",
            "x": 96,
            "y": 32,
            "w": 16,
            "h": 16
          },
          {
            "src": "assets/sprites/sources/donkey-original.png",
            "x": 112,
            "y": 32,
            "w": 16,
            "h": 16
          }
        ],
        "cx": 8,
        "bottom": 16,
        "top": 1,
        "width": 10,
        "flip": false
      },
      "left": {
        "frames": [
          {
            "src": "assets/sprites/sources/donkey-original.png",
            "x": 96,
            "y": 48,
            "w": 16,
            "h": 16
          },
          {
            "src": "assets/sprites/sources/donkey-original.png",
            "x": 112,
            "y": 48,
            "w": 16,
            "h": 16
          }
        ],
        "cx": 8,
        "bottom": 15,
        "top": 0,
        "width": 16,
        "flip": false
      }
    }
  },
  "lamb": {
    "scale": 0.85,
    "poses": {
      "up": {
        "frames": [
          {
            "src": "assets/sprites/sources/sheep_walk.png",
            "x": 0,
            "y": 0,
            "w": 128,
            "h": 128
          },
          {
            "src": "assets/sprites/sources/sheep_walk.png",
            "x": 128,
            "y": 0,
            "w": 128,
            "h": 128
          },
          {
            "src": "assets/sprites/sources/sheep_walk.png",
            "x": 256,
            "y": 0,
            "w": 128,
            "h": 128
          },
          {
            "src": "assets/sprites/sources/sheep_walk.png",
            "x": 384,
            "y": 0,
            "w": 128,
            "h": 128
          }
        ],
        "cx": 63.5,
        "bottom": 89,
        "top": 39,
        "width": 27,
        "flip": false
      },
      "left": {
        "frames": [
          {
            "src": "assets/sprites/sources/sheep_walk.png",
            "x": 0,
            "y": 128,
            "w": 128,
            "h": 128
          },
          {
            "src": "assets/sprites/sources/sheep_walk.png",
            "x": 128,
            "y": 128,
            "w": 128,
            "h": 128
          },
          {
            "src": "assets/sprites/sources/sheep_walk.png",
            "x": 256,
            "y": 128,
            "w": 128,
            "h": 128
          },
          {
            "src": "assets/sprites/sources/sheep_walk.png",
            "x": 384,
            "y": 128,
            "w": 128,
            "h": 128
          }
        ],
        "cx": 61.5,
        "bottom": 83,
        "top": 43,
        "width": 49,
        "flip": false
      },
      "down": {
        "frames": [
          {
            "src": "assets/sprites/sources/sheep_walk.png",
            "x": 0,
            "y": 256,
            "w": 128,
            "h": 128
          },
          {
            "src": "assets/sprites/sources/sheep_walk.png",
            "x": 128,
            "y": 256,
            "w": 128,
            "h": 128
          },
          {
            "src": "assets/sprites/sources/sheep_walk.png",
            "x": 256,
            "y": 256,
            "w": 128,
            "h": 128
          },
          {
            "src": "assets/sprites/sources/sheep_walk.png",
            "x": 384,
            "y": 256,
            "w": 128,
            "h": 128
          }
        ],
        "cx": 63.5,
        "bottom": 89,
        "top": 47,
        "width": 27,
        "flip": false
      },
      "right": {
        "frames": [
          {
            "src": "assets/sprites/sources/sheep_walk.png",
            "x": 0,
            "y": 384,
            "w": 128,
            "h": 128
          },
          {
            "src": "assets/sprites/sources/sheep_walk.png",
            "x": 128,
            "y": 384,
            "w": 128,
            "h": 128
          },
          {
            "src": "assets/sprites/sources/sheep_walk.png",
            "x": 256,
            "y": 384,
            "w": 128,
            "h": 128
          },
          {
            "src": "assets/sprites/sources/sheep_walk.png",
            "x": 384,
            "y": 384,
            "w": 128,
            "h": 128
          }
        ],
        "cx": 66.5,
        "bottom": 83,
        "top": 43,
        "width": 49,
        "flip": false
      }
    }
  },
  "chick": {
    "scale": 1.6,
    "poses": {
      "left": {
        "frames": [
          {
            "src": "assets/sprites/sources/chick.png",
            "x": 48,
            "y": 0,
            "w": 24,
            "h": 24
          },
          {
            "src": "assets/sprites/sources/chick.png",
            "x": 72,
            "y": 0,
            "w": 24,
            "h": 24
          },
          {
            "src": "assets/sprites/sources/chick.png",
            "x": 96,
            "y": 0,
            "w": 24,
            "h": 24
          },
          {
            "src": "assets/sprites/sources/chick.png",
            "x": 120,
            "y": 0,
            "w": 24,
            "h": 24
          },
          {
            "src": "assets/sprites/sources/chick.png",
            "x": 144,
            "y": 0,
            "w": 24,
            "h": 24
          }
        ],
        "cx": 12,
        "bottom": 24,
        "top": 4,
        "width": 22,
        "flip": false
      },
      "down": {
        "frames": [
          {
            "src": "assets/sprites/sources/chick.png",
            "x": 48,
            "y": 24,
            "w": 24,
            "h": 24
          },
          {
            "src": "assets/sprites/sources/chick.png",
            "x": 72,
            "y": 24,
            "w": 24,
            "h": 24
          },
          {
            "src": "assets/sprites/sources/chick.png",
            "x": 96,
            "y": 24,
            "w": 24,
            "h": 24
          },
          {
            "src": "assets/sprites/sources/chick.png",
            "x": 120,
            "y": 24,
            "w": 24,
            "h": 24
          },
          {
            "src": "assets/sprites/sources/chick.png",
            "x": 144,
            "y": 24,
            "w": 24,
            "h": 24
          }
        ],
        "cx": 12,
        "bottom": 24,
        "top": 4,
        "width": 14,
        "flip": false
      },
      "up": {
        "frames": [
          {
            "src": "assets/sprites/sources/chick.png",
            "x": 48,
            "y": 48,
            "w": 24,
            "h": 24
          },
          {
            "src": "assets/sprites/sources/chick.png",
            "x": 72,
            "y": 48,
            "w": 24,
            "h": 24
          },
          {
            "src": "assets/sprites/sources/chick.png",
            "x": 96,
            "y": 48,
            "w": 24,
            "h": 24
          },
          {
            "src": "assets/sprites/sources/chick.png",
            "x": 120,
            "y": 48,
            "w": 24,
            "h": 24
          },
          {
            "src": "assets/sprites/sources/chick.png",
            "x": 144,
            "y": 48,
            "w": 24,
            "h": 24
          }
        ],
        "cx": 12,
        "bottom": 24,
        "top": 4,
        "width": 14,
        "flip": false
      },
      "right": {
        "frames": [
          {
            "src": "assets/sprites/sources/chick.png",
            "x": 48,
            "y": 0,
            "w": 24,
            "h": 24
          },
          {
            "src": "assets/sprites/sources/chick.png",
            "x": 72,
            "y": 0,
            "w": 24,
            "h": 24
          },
          {
            "src": "assets/sprites/sources/chick.png",
            "x": 96,
            "y": 0,
            "w": 24,
            "h": 24
          },
          {
            "src": "assets/sprites/sources/chick.png",
            "x": 120,
            "y": 0,
            "w": 24,
            "h": 24
          },
          {
            "src": "assets/sprites/sources/chick.png",
            "x": 144,
            "y": 0,
            "w": 24,
            "h": 24
          }
        ],
        "cx": 12,
        "bottom": 24,
        "top": 4,
        "width": 22,
        "flip": true
      }
    }
  }
};
